version: '3'
services:
  bot:
    build: .
    depends_on:
      - database
    env_file:
      - env.env
    restart: always

  database:
    image: postgres
    restart: always
    env_file:
      - env.env
    ports:
      - 8012:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data

volumes:
  db: